name: Deploy frontend to Firebase Hosting on push

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4
      - run: pwd
      - run: cd front/bebidas
      - run: pwd
      - uses: actions/setup-node@v4
        with:
          node-version: 12.22.12

      - run: cd front/bebidas

      # Paso 3: Instalar dependencias y construir el proyecto Angular
      #- run: npm install && npm run build --if-present

      #- run: npm install -g firebase-tools@7.16.2

      - run: ls

      - run: pwd

      # Paso 3: Desplegar el proyecto en Firebase Hosting
      #- uses: FirebaseExtended/action-hosting-deploy@v0
      # with:
      #  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      # projectId: bebidas-5db80
      #channelId: live
      #entryPoint: bebidas
