name: Deploy frontend to Firebase Hosting on push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4

      # Paso 2: Instalar node
      - uses: actions/setup-node@v4
        with:
          node-version: 12.22.12

      # Paso 3: Instalar dependencias
      - run: npm install
        working-directory: front/bebidas

      # Paso 4: Construir el proyecto Angular
      - run: npm run build --if-present
        working-directory: front/bebidas

      # Paso 5: Instalar firebase cli
      - run: npm install -g firebase-tools@7.16.2

      # Paso 6: Desplegar frontend
      - run: firebase deploy --only hosting --project bebidas-5db80
        working-directory: front/bebidas
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
